data = [
"Group: Black Boats",
"data-id: abstract",
"data-img: /media/oxgerncy/black-boats.jpg",
"data-title: Black Boats",
"data-description: Acrylic on cardboard",
"data-price: 50",
"data-width: 20",
"data-height: 21",
"data-framed: Not Framed",
"Group: Black On White",
"data-id: abstract",
"data-img: /media/fesjirrr/black-on-white.jpg",
"data-title: Black On White",
"data-description: Acrylic on canvas",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Black Stripes",
"data-id: abstract",
"data-img: /media/kurjicar/black-stripes.jpg",
"data-title: Black Stripes",
"data-description: Acrylic on canvas",
"data-price: 175",
"data-width: 70",
"data-height: 50",
"data-framed: Not Framed",
"Group: Gray Square",
"data-id: abstract",
"data-img: /media/prol0do0/gray-square.jpg",
"data-title: Gray Square",
"data-description: Paper collage",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Harmony In White",
"data-id: abstract",
"data-img: /media/lwtl20gj/harmony-in-white.jpg",
"data-title: Harmony In White",
"data-description: Acrylic on canvas",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Mystic Sky",
"data-id: abstract",
"data-img: /media/udlaohdg/mystic-sky.jpg",
"data-title: Mystic Sky",
"data-description: Paper collage and paint",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Red L",
"data-id: abstract",
"data-img: /media/ljdnw2cp/red-l.jpg",
"data-title: Red L",
"data-description: Paper collage",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Red Stripe",
"data-id: abstract",
"data-img: /media/e42bbbhg/red-stripe.jpg",
"data-title: Red Stripe",
"data-description: Paper collage",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Study In Gray",
"data-id: abstract",
"data-img: /media/hshaeewk/study-in-gray.jpg",
"data-title: Study In Gray",
"data-description: Collage and paint",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: White Boats",
"data-id: abstract",
"data-img: /media/huafqohp/white-boats.jpg",
"data-title: White Boats",
"data-description: Acrylic on cardboard",
"data-price: 40",
"data-width: 18",
"data-height: 21",
"data-framed: Not Framed",
"Group: White Field 2",
"data-id: abstract",
"data-img: /media/vjbhn0xb/white-field-2.jpg",
"data-title: White Field 2",
"data-description: Paper collage",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: White Field",
"data-id: abstract",
"data-img: /media/rkcfucoy/white-field.jpg",
"data-title: White Field",
"data-description: Paper collage",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: White Post",
"data-id: abstract",
"data-img: /media/ybqleuba/white-post.jpg",
"data-title: White Post",
"data-description: Paper collage and paint",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Yellow Corner",
"data-id: abstract",
"data-img: /media/wiqffgcx/yellow-corner.jpg",
"data-title: Yellow Corner",
"data-description: Acrylic on canvas",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Yellow Streak",
"data-id: abstract",
"data-img: /media/nbdnc1ds/yellow-streak.jpg",
"data-title: Yellow Streak",
"data-description: Acrylic on canvas",
"data-price: 150",
"data-width: 40",
"data-height: 51",
"data-framed: Not Framed",
"Group: IMG 20200521 133017 Kindlephoto 267415499",
"data-id: abstract",
"data-img: /media/gb5dyepp/img_20200521_133017_kindlephoto-267415499.jpg",
"data-title: IMG 20200521 133017 Kindlephoto 267415499",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: IMG 20200521 133223 Kindlephoto 267580336",
"data-id: abstract",
"data-img: /media/u5fneizz/img_20200521_133223_kindlephoto-267580336.jpg",
"data-title: IMG 20200521 133223 Kindlephoto 267580336",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: IMG 20200521 133116 Kindlephoto 267490243",
"data-id: abstract",
"data-img: /media/wu4eubjz/img_20200521_133116_kindlephoto-267490243.jpg",
"data-title: IMG 20200521 133116 Kindlephoto 267490243",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: One",
"data-id: collage",
"data-img: /media/colnxcyo/one.jpg",
"data-title: One",
"data-description: Paper collage",
"data-price: 100",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Three",
"data-id: collage",
"data-img: /media/330nvyse/three.jpg",
"data-title: Three",
"data-description: Paper collage",
"data-price: 100",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Two",
"data-id: collage",
"data-img: /media/5l3djw3b/two.jpg",
"data-title: Two",
"data-description: Paper collage",
"data-price: 100",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Clyde Valley",
"data-id: landscapes",
"data-img: /media/hiibhvte/clyde-valley.jpg",
"data-title: Clyde Valley",
"data-description: Acrylic on canvas",
"data-price: 240",
"data-width: 40",
"data-height: 50",
"data-framed: Not Framed",
"Group: Clyde Walkway 2",
"data-id: landscapes",
"data-img: /media/wexjgsdc/clyde-walkway-2.jpg",
"data-title: Clyde Walkway 2",
"data-description: Acrylic on canvas",
"data-price: 145",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Clyde Walkway",
"data-id: landscapes",
"data-img: /media/c1amytwn/clyde-walkway.jpg",
"data-title: Clyde Walkway",
"data-description: Acrylic on canvas",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Falls Of Clyde 2",
"data-id: landscapes",
"data-img: /media/nvukbfig/falls-of-clyde-2.jpg",
"data-title: Falls Of Clyde 2",
"data-description: Acrylic on canvas",
"data-price: 280",
"data-width: 40",
"data-height: 50",
"data-framed: Not Framed",
"Group: Falls Of Clyde Bonnington Linn",
"data-id: landscapes",
"data-img: /media/dyfnfqbt/falls-of-clyde-bonnington-linn.jpg",
"data-title: Falls Of Clyde Bonnington Linn",
"data-description: Acrylic on canvas",
"data-price: 290",
"data-width: 40",
"data-height: 57",
"data-framed: Not Framed",
"Group: Falls Of Clyde",
"data-id: landscapes",
"data-img: /media/tsgjjqcd/falls-of-clyde.jpg",
"data-title: Falls Of Clyde",
"data-description: Acrylic on canvas",
"data-price: 380",
"data-width: 50",
"data-height: 70",
"data-framed: Not Framed",
"Group: Findochty Harbour",
"data-id: landscapes",
"data-img: /media/ialentyi/findochty-harbour.jpg",
"data-title: Findochty Harbour",
"data-description: Acrylic on canvas",
"data-price: 170",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Frosty Garden",
"data-id: landscapes",
"data-img: /media/ln3ngqwq/frosty-garden.jpg",
"data-title: Frosty Garden",
"data-description: Acrylic on canvas",
"data-price: 360",
"data-width: 57",
"data-height: 67",
"data-framed: Framed",
"Group: Frosty Morning Clyde Valley",
"data-id: landscapes",
"data-img: /media/ygced2jv/frosty-morning-clyde-valley.jpg",
"data-title: Frosty Morning Clyde Valley",
"data-description: Acrylic on Canvas",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Frosy Morning Carnwath",
"data-id: landscapes",
"data-img: /media/f2wnbd1x/frosy-morning-carnwath.jpg",
"data-title: Frosy Morning Carnwath",
"data-description: Acrylic on canvas",
"data-price: 280",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Lilac Copse",
"data-id: landscapes",
"data-img: /media/wxmam4dw/lilac-copse.jpg",
"data-title: Lilac Copse",
"data-description: Acrylic on canvas",
"data-price: 120",
"data-width: 23",
"data-height: 30",
"data-framed: Not Framed",
"Group: River Clyde 2",
"data-id: landscapes",
"data-img: /media/djgkk3ms/river-clyde-2.jpg",
"data-title: River Clyde 2",
"data-description: Heavily textured acrylic paint on canvas",
"data-price: 145",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: River Clyde Winter",
"data-id: landscapes",
"data-img: /media/wwzgubye/river-clyde-winter.jpg",
"data-title: River Clyde Winter",
"data-description: Acrylic on Canvas",
"data-price: 350",
"data-width: 0",
"data-height: 0",
"data-framed: Framed",
"Group: River Clyde",
"data-id: landscapes",
"data-img: /media/m2uno0sq/river-clyde.jpg",
"data-title: River Clyde",
"data-description: Acrylic on board",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Snowscape",
"data-id: landscapes",
"data-img: /media/rgsnhjws/snowscape.jpg",
"data-title: Snowscape",
"data-description: Acrylic on canvas",
"data-price: 175",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"data-id: plasterPaintings",
"data-img: /media/yp1nouec/snowscape.jpg",
"data-title: Snowscape",
"data-description: Plaster, acrylic paint on MDF.",
"data-price: 130",
"data-width: 25",
"data-height: 30",
"data-framed: Not Framed",
"Group: The Red Boat",
"data-id: landscapes",
"data-img: /media/ztqdlq1m/the-red-boat.jpg",
"data-title: The Red Boat",
"data-description: Acrylic on Board",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Winter River Clyde",
"data-id: landscapes",
"data-img: /media/gqaazcir/winter-river-clyde.jpg",
"data-title: Winter River Clyde",
"data-description: Watercolour on paper",
"data-price: 50",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: IMG 20210312 161841",
"data-id: landscapes",
"data-img: /media/1gab1t51/img_20210312_161841.jpg",
"data-title: IMG 20210312 161841",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: 20211026 135812",
"data-id: landscapes",
"data-img: /media/r2ahcjzf/20211026_135812.jpg",
"data-title: 20211026 135812",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: 20211028 123355",
"data-id: landscapes",
"data-img: /media/qpmfadfp/20211028_123355.jpg",
"data-title: 20211028 123355",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: By The Clyde",
"data-id: lockdown",
"data-img: /media/ztmd3nh1/by-the-clyde.jpg",
"data-title: By The Clyde",
"data-description: Watercolour and pen and ink",
"data-price: 100",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"data-id: oilPastels",
"data-img: /media/c11dpfoq/by-the-clyde.jpg",
"data-title: By The Clyde",
"data-description: Tree by the river Clyde, oil pastel on black sugar paper",
"data-price: 100",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Dead Tree",
"data-id: lockdown",
"data-img: /media/lullyw4u/dead-tree.jpg",
"data-title: Dead Tree",
"data-description: Watercolour and pen and ink",
"data-price: 100",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Imagined Landscape",
"data-id: lockdown",
"data-img: /media/32lkdwcd/imagined-landscape.jpg",
"data-title: Imagined Landscape",
"data-description: Imagined landscape based upon Tinto Hill. A slightly more expressive painting with lots of impostors paint",
"data-price: 300",
"data-width: 30",
"data-height: 40",
"data-framed: Not Framed",
"Group: Towards The Clyde Valley",
"data-id: lockdown",
"data-img: /media/msodq4ss/towards-the-clyde-valley.jpg",
"data-title: Towards The Clyde Valley",
"data-description: Acrylic painted at scene,looking towards the Clyde Valley",
"data-price: 300",
"data-width: 30",
"data-height: 40",
"data-framed: Not Framed",
"Group: Tree 1",
"data-id: lockdown",
"data-img: /media/2gbd0o14/tree-1.jpg",
"data-title: Tree 1",
"data-description: Watercolour and pen and ink",
"data-price: 100",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Tree 2",
"data-id: lockdown",
"data-img: /media/v3zpsqti/tree-2.jpg",
"data-title: Tree 2",
"data-description: By the Clyde",
"data-price: 100",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Tree 3",
"data-id: lockdown",
"data-img: /media/dpaauf0b/tree-3.jpg",
"data-title: Tree 3",
"data-description: Over the bing",
"data-price: 100",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Tree 4",
"data-id: lockdown",
"data-img: /media/zqoleh4c/tree-4.jpg",
"data-title: Tree 4",
"data-description: Watercolour and pen and ink",
"data-price: 100",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Tree",
"data-id: lockdown",
"data-img: /media/xvshhtrn/tree.jpg",
"data-title: Tree",
"data-description: Watercolour and ink",
"data-price: 100",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"data-id: oilPastels",
"data-img: /media/2mkkaxua/tree.jpg",
"data-title: Tree",
"data-description: Oil pastel on paper",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Vista",
"data-id: lockdown",
"data-img: /media/tfcpwqmi/vista.jpg",
"data-title: Vista",
"data-description: Watercolour painted an alien air",
"data-price: 100",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: IMG 20200513 145437 Kindlephoto 29950044",
"data-id: lockdown",
"data-img: /media/utkijelm/img_20200513_145437_kindlephoto-29950044.jpg",
"data-title: IMG 20200513 145437 Kindlephoto 29950044",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: IMG 20200630 125255 Kindlephoto 161020139",
"data-id: lockdown",
"data-img: /media/uvcozgmv/img_20200630_125255_kindlephoto-161020139.jpg",
"data-title: IMG 20200630 125255 Kindlephoto 161020139",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: IMG 20200508 155431 Kindlephoto 91266626",
"data-id: lockdown",
"data-img: /media/0raijwsh/img_20200508_155431_kindlephoto-91266626.jpg",
"data-title: IMG 20200508 155431 Kindlephoto 91266626",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: IMG 20200630 125321 Kindlephoto 160944122",
"data-id: lockdown",
"data-img: /media/rggesir3/img_20200630_125321_kindlephoto-160944122.jpg",
"data-title: IMG 20200630 125321 Kindlephoto 160944122",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: IMG 20200508 155512 Kindlephoto 91688218",
"data-id: lockdown",
"data-img: /media/1kxlocf3/img_20200508_155512_kindlephoto-91688218.jpg",
"data-title: IMG 20200508 155512 Kindlephoto 91688218",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Clouds 2",
"data-id: oilPastels",
"data-img: /media/stjhorl4/clouds-2.jpg",
"data-title: Clouds 2",
"data-description: Oil pastel on paper",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Clouds 3",
"data-id: oilPastels",
"data-img: /media/r12gqlkg/clouds-3.jpg",
"data-title: Clouds 3",
"data-description: Oil pastel on paper",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Clouds 4",
"data-id: oilPastels",
"data-img: /media/dryblm3w/clouds-4.jpg",
"data-title: Clouds 4",
"data-description: Oil pastel on paper",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Clouds 5",
"data-id: oilPastels",
"data-img: /media/cf2ncwx4/clouds-5.jpg",
"data-title: Clouds 5",
"data-description: Oil pastel on paper",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Clouds",
"data-id: oilPastels",
"data-img: /media/ttnhaonr/clouds.jpg",
"data-title: Clouds",
"data-description: Oil pastel on paper",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Coldingham Bay",
"data-id: oilPastels",
"data-img: /media/qe4n3gza/coldingham-bay.jpg",
"data-title: Coldingham Bay",
"data-description: Oil pastel on paper",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Self Portrait",
"data-id: oilPastels",
"data-img: /media/2jnnu4sd/self-portrait.jpg",
"data-title: Self Portrait",
"data-description: Oil pastel on black sugar paper",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Skull 2",
"data-id: oilPastels",
"data-img: /media/dttmo0wu/skull-2.jpg",
"data-title: Skull 2",
"data-description: Oil pastel on black sugar paper",
"data-price: 100",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Skull 3",
"data-id: oilPastels",
"data-img: /media/cculyluf/skull-3.jpg",
"data-title: Skull 3",
"data-description: Oil Pastel",
"data-price: 100",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Skull",
"data-id: oilPastels",
"data-img: /media/f4gjq42o/skull.jpg",
"data-title: Skull",
"data-description: Oil pastel on black sugar paper",
"data-price: 120",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Weird Tree",
"data-id: oilPastels",
"data-img: /media/sjmbhibi/weird-tree.jpg",
"data-title: Weird Tree",
"data-description: Oil pastel on black sugar paper",
"data-price: 100",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Image",
"data-id: oilPastels",
"data-img: /media/fnnfhmjt/image.jpg",
"data-title: Image",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: 20220922 155359",
"data-id: oilPastels",
"data-img: /media/exaj2lah/20220922_155359.jpg",
"data-title: 20220922 155359",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: 20221110 143932",
"data-id: oilPastels",
"data-img: /media/mnidey2q/20221110_143932.jpg",
"data-title: 20221110 143932",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: 20221110 145755",
"data-id: oilPastels",
"data-img: /media/scgjbhse/20221110_145755.jpg",
"data-title: 20221110 145755",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: 20221230 150147",
"data-id: oilPastels",
"data-img: /media/ualjfb5f/20221230_150147.jpg",
"data-title: 20221230 150147",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Pig",
"data-id: photos",
"data-img: /media/51mdcsid/pig.jpg",
"data-title: Pig",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Sheep",
"data-id: photos",
"data-img: /media/huchovb0/sheep.jpg",
"data-title: Sheep",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Squinty Pole",
"data-id: photos",
"data-img: /media/cojj4114/squinty-pole.jpg",
"data-title: Squinty Pole",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Wooly Pig",
"data-id: photos",
"data-img: /media/5kmb30in/wooly-pig.jpg",
"data-title: Wooly Pig",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Ailsa Craig",
"data-id: plasterPaintings",
"data-img: /media/lbadowc0/ailsa-craig.jpg",
"data-title: Ailsa Craig",
"data-description: Plaster, acrylic paint on MDF",
"data-price: 130",
"data-width: 22",
"data-height: 31",
"data-framed: Not Framed",
"Group: Landscape With Cloud",
"data-id: plasterPaintings",
"data-img: /media/0jnd2cqt/landscape-with-cloud.jpg",
"data-title: Landscape With Cloud",
"data-description: Plaster, acrylic paint on MDF.",
"data-price: 130",
"data-width: 25",
"data-height: 30",
"data-framed: Not Framed",
"Group: Purple Sky",
"data-id: plasterPaintings",
"data-img: /media/weab42ij/purple-sky.jpg",
"data-title: Purple Sky",
"data-description: Plaster, acrylic paint on board",
"data-price: 120",
"data-width: 20",
"data-height: 25",
"data-framed: Not Framed",
"Group: Red Landscape",
"data-id: plasterPaintings",
"data-img: /media/1uxbyx5q/red-landscape.jpg",
"data-title: Red Landscape",
"data-description: Plaster, acrylic paint on MDF.",
"data-price: 130",
"data-width: 25",
"data-height: 30",
"data-framed: Not Framed",
"Group: Trees In The Distance",
"data-id: plasterPaintings",
"data-img: /media/i5djizp2/trees-in-the-distance.jpg",
"data-title: Trees In The Distance",
"data-description: Plaster, acrylic paint on MDF.",
"data-price: 140",
"data-width: 30",
"data-height: 25",
"data-framed: Not Framed",
"Group: Trees On The Hill",
"data-id: plasterPaintings",
"data-img: /media/55thyxuj/trees-on-the-hill.jpg",
"data-title: Trees On The Hill",
"data-description: Plaster with acrylic paint on MDF(medium density fibreboard)",
"data-price: 145",
"data-width: 25",
"data-height: 31",
"data-framed: Not Framed",
"Group: 20221230 150455",
"data-id: plasterPaintings",
"data-img: /media/s1jfshvw/20221230_150455.jpg",
"data-title: 20221230 150455",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: 20221230 150427 (1)",
"data-id: plasterPaintings",
"data-img: /media/0kwdy34h/20221230_150427.jpg",
"data-title: 20221230 150427 (1)",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: 20220704 151409",
"data-id: plasterPaintings",
"data-img: /media/o3zftxcw/20220704_151409.jpg",
"data-title: 20220704 151409",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: 20221230 150417 (1)",
"data-id: plasterPaintings",
"data-img: /media/ws2hqask/20221230_150417.jpg",
"data-title: 20221230 150417 (1)",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: 20221230 150404 (1)",
"data-id: plasterPaintings",
"data-img: /media/2wcf5fah/20221230_150404.jpg",
"data-title: 20221230 150404 (1)",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: 20220627 163028",
"data-id: plasterPaintings",
"data-img: /media/nhuby4mw/20220627_163028.jpg",
"data-title: 20220627 163028",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: 20220922 152101",
"data-id: plasterPaintings",
"data-img: /media/1gbdu3qf/20220922_152101.jpg",
"data-title: 20220922 152101",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Original 5Ec807d4 08F3 43A7 A3fa 96F634cfaa22 20220605 190015",
"data-id: plasterPaintings",
"data-img: /media/5xpdxugn/original_5ec807d4-08f3-43a7-a3fa-96f634cfaa22_20220605_190015.jpg",
"data-title: Original 5Ec807d4 08F3 43A7 A3fa 96F634cfaa22 20220605 190015",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Bird's Eye View",
"data-id: stAbbs",
"data-img: /media/4tolrgag/bird-s-eye-view.jpg",
"data-title: Bird's Eye View",
"data-description: Watercolour on paper",
"data-price: 60",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Blue Boat",
"data-id: stAbbs",
"data-img: /media/1bhjoti0/blue-boat.jpg",
"data-title: Blue Boat",
"data-description: Watercolour and sharpies on paper",
"data-price: 75",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Fishing Boat",
"data-id: stAbbs",
"data-img: /media/24abdvpg/fishing-boat.jpg",
"data-title: Fishing Boat",
"data-description: Watercolour on paper",
"data-price: 60",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Fishing Boats",
"data-id: stAbbs",
"data-img: /media/g4rlf3fh/fishing-boats.jpg",
"data-title: Fishing Boats",
"data-description: Watercolour on paper",
"data-price: 95",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Harbour, St. Abbs",
"data-id: stAbbs",
"data-img: /media/q05bwclq/harbour-st-abbs.jpg",
"data-title: Harbour, St. Abbs",
"data-description: Watercolour on paper",
"data-price: 75",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Harbour",
"data-id: stAbbs",
"data-img: /media/2mkfnqn2/harbour.jpg",
"data-title: Harbour",
"data-description: Pen and Ink drawing",
"data-price: 60",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Red Fishing Boat",
"data-id: stAbbs",
"data-img: /media/x03jqmff/red-fishing-boat.jpg",
"data-title: Red Fishing Boat",
"data-description: Acrylic on canvas paper",
"data-price: 95",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Red Reflections",
"data-id: stAbbs",
"data-img: /media/mbwluenm/red-reflections.jpg",
"data-title: Red Reflections",
"data-description: Acrylic on canvas paper",
"data-price: 90",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Telephone Box",
"data-id: stAbbs",
"data-img: /media/ah2irn2j/telephone-box.jpg",
"data-title: Telephone Box",
"data-description: Watercolour on paper",
"data-price: 65",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: White Cottage",
"data-id: stAbbs",
"data-img: /media/gwyjntwj/white-cottage.jpg",
"data-title: White Cottage",
"data-description: Watercolour on paper",
"data-price: 55",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: IMG 20161020 123830",
"data-id: stAbbs",
"data-img: /media/ugjnjpo4/img_20161020_123830.jpg",
"data-title: IMG 20161020 123830",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: IMG 20160706 113314",
"data-id: stAbbs",
"data-img: /media/npognpzx/img_20160706_113314.jpg",
"data-title: IMG 20160706 113314",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Blue 2",
"data-id: stillLife",
"data-img: /media/uytnjygf/blue-2.jpg",
"data-title: Blue 2",
"data-description: Acrylic on canvas",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Blue Table",
"data-id: stillLife",
"data-img: /media/2otajz00/blue-table.jpg",
"data-title: Blue Table",
"data-description: Acrylic on canvas",
"data-price: 260",
"data-width: 50",
"data-height: 60",
"data-framed: Not Framed",
"Group: Blue",
"data-id: stillLife",
"data-img: /media/5y5dlptk/blue.jpg",
"data-title: Blue",
"data-description: Acrylic on canvas",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Dutch Still Life",
"data-id: stillLife",
"data-img: /media/vncdezpk/dutch-still-life.jpg",
"data-title: Dutch Still Life",
"data-description: Acrylic on canvas",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Framed",
"Group: Pink Still Life",
"data-id: stillLife",
"data-img: /media/nkijbmnk/pink-still-life.jpg",
"data-title: Pink Still Life",
"data-description: Acrylic on canvas",
"data-price: 100",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Purple Table",
"data-id: stillLife",
"data-img: /media/hysnxpc0/purple-table.jpg",
"data-title: Purple Table",
"data-description: Acrylic on canvas",
"data-price: 275",
"data-width: 50",
"data-height: 60",
"data-framed: Not Framed",
"Group: Red Table",
"data-id: stillLife",
"data-img: /media/lpenngx1/red-table.jpg",
"data-title: Red Table",
"data-description: Acrylic on canvas",
"data-price: 100",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Squinty Vase Of Flowers",
"data-id: stillLife",
"data-img: /media/nkhemdpv/squinty-vase-of-flowers.jpg",
"data-title: Squinty Vase Of Flowers",
"data-description: Acrylic on canvas",
"data-price: 300",
"data-width: 50",
"data-height: 70",
"data-framed: Not Framed",
"Group: Sunflower",
"data-id: stillLife",
"data-img: /media/vqtnxl4q/sunflower.jpg",
"data-title: Sunflower",
"data-description: Acrylic on canvas",
"data-price: 240",
"data-width: 40",
"data-height: 50",
"data-framed: Not Framed",
"Group: Tulips",
"data-id: stillLife",
"data-img: /media/04sp3ufc/tulips.jpg",
"data-title: Tulips",
"data-description: Acrylic on canvas",
"data-price: 300",
"data-width: 50",
"data-height: 70",
"data-framed: Not Framed",
"Group: Vase Of Flowers",
"data-id: stillLife",
"data-img: /media/az3dyxpe/vase-of-flowers.jpg",
"data-title: Vase Of Flowers",
"data-description: Acrylic on canvas",
"data-price: 275",
"data-width: 50",
"data-height: 60",
"data-framed: Not Framed",
"Group: Blue Sky",
"data-id: italy",
"data-img: /media/aydh000a/blue-sky.jpg",
"data-title: Blue Sky",
"data-description: Acrylic on paper",
"data-price: 85",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Padua",
"data-id: italy",
"data-img: /media/wt3g0zec/padua.jpg",
"data-title: Padua",
"data-description: Watercolour on paper",
"data-price: 65",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Pink Building",
"data-id: italy",
"data-img: /media/s3rgkfxd/pink-building.jpg",
"data-title: Pink Building",
"data-description: Acrlyic on paper",
"data-price: 75",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Pink Palace",
"data-id: italy",
"data-img: /media/e1pbndsj/pink-palace.jpg",
"data-title: Pink Palace",
"data-description: Acrylic on paper",
"data-price: 85",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Red Pavement",
"data-id: italy",
"data-img: /media/qoclisrj/red-pavement.jpg",
"data-title: Red Pavement",
"data-description: Acrylic on paper",
"data-price: 75",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Squinty Building",
"data-id: italy",
"data-img: /media/dxspmwsa/squinty-building.jpg",
"data-title: Squinty Building",
"data-description: Acrylic on paper",
"data-price: 75",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Street Light",
"data-id: italy",
"data-img: /media/2dqculdh/street-light.jpg",
"data-title: Street Light",
"data-description: Watercolour on paper",
"data-price: 60",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Street Scene",
"data-id: italy",
"data-img: /media/xbig12ck/street-scene.jpg",
"data-title: Street Scene",
"data-description: Watercolour on paper",
"data-price: 55",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Study",
"data-id: italy",
"data-img: /media/lrxj1xi4/study.jpg",
"data-title: Study",
"data-description: Pen and wash on paper",
"data-price: 60",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Venetian Building",
"data-id: italy",
"data-img: /media/cadbuwdy/venetian-building.jpg",
"data-title: Venetian Building",
"data-description: Watercolour painting",
"data-price: 60",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Venetian Buildings",
"data-id: italy",
"data-img: /media/oomf42a0/venetian-buildings.jpg",
"data-title: Venetian Buildings",
"data-description: Watercolour on paper",
"data-price: 55",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Venetian Street Scene",
"data-id: italy",
"data-img: /media/s5whdfwj/venetian-street-scene.jpg",
"data-title: Venetian Street Scene",
"data-description: Pen drawing",
"data-price: 75",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Venetian Theatre",
"data-id: italy",
"data-img: /media/z30fiohe/venetian-theatre.jpg",
"data-title: Venetian Theatre",
"data-description: Watercolour on paper",
"data-price: 75",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: View From Hotel",
"data-id: italy",
"data-img: /media/trvju51b/view-from-hotel.jpg",
"data-title: View From Hotel",
"data-description: Watercolour",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: IMG 20161020 123403",
"data-id: italy",
"data-img: /media/ewla5jqs/img_20161020_123403.jpg",
"data-title: IMG 20161020 123403",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: IMG 20180504 170620",
"data-id: italy",
"data-img: /media/e5hnd4g1/img_20180504_170620.jpg",
"data-title: IMG 20180504 170620",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: IMG 20150404 182158~2",
"data-id: italy",
"data-img: /media/hquc2oev/img_20150404_182158-2.jpg",
"data-title: IMG 20150404 182158~2",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: IMG 20150404 182141~2~2",
"data-id: italy",
"data-img: /media/44cfvt5f/img_20150404_182141-2-2.jpg",
"data-title: IMG 20150404 182141~2~2",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: IMG 20150404 182425~2",
"data-id: italy",
"data-img: /media/53tjskvo/img_20150404_182425-2.jpg",
"data-title: IMG 20150404 182425~2",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: IMG 20180504 170703 1",
"data-id: italy",
"data-img: /media/p3zbtekt/img_20180504_170703_1.jpg",
"data-title: IMG 20180504 170703 1",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: 2012 09 02 16.01.09",
"data-id: italy",
"data-img: /media/1tclrcxk/2012-09-02-16-01-09.jpg",
"data-title: 2012 09 02 16.01.09",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: IMG 20150404 182518~2~2",
"data-id: italy",
"data-img: /media/v50ntqoi/img_20150404_182518-2-2.jpg",
"data-title: IMG 20150404 182518~2~2",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: IMG 20150404 182555~2",
"data-id: italy",
"data-img: /media/i0bfky3l/img_20150404_182555-2.jpg",
"data-title: IMG 20150404 182555~2",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed ",
]

# Initialize a list to store attribute dictionaries for each group
group_attributes = []

# Initialize a dictionary to hold the current group's attributes
current_attributes = {}

# Iterate over the data list
for item in data:
    if item.startswith("Group: "):
        # Store previous group's attributes and reset the current attributes dictionary
        if current_attributes:
            group_attributes.append(current_attributes)
        current_attributes = {'Group': item.replace("Group: ", "")}
    else:
        key, value = item.split(': ', 1)
        current_attributes[key] = value

# Append the last group's attributes
if current_attributes:
    group_attributes.append(current_attributes)

# Generate and print the populated templates for each group
for attributes in group_attributes:
    template = f"${{require('/partials/card.html') title=`{attributes.get('data-title', '')}` id=`{attributes.get('data-id', '')}` img=`{attributes.get('data-img', '')}` description=`{attributes.get('data-description', '')}` price=`{attributes.get('data-price', '')}` width=`{attributes.get('data-width', '')}` height=`{attributes.get('data-height', '')}` frame=`{attributes.get('data-framed', '')}`}}"
    print(template)
