data = [
"Group: Black Boats",
"data-id: abstract",
"data-img: /img/black-boats.jpg",
"data-title: Black Boats",
"data-description: Acrylic on cardboard",
"data-price: 50",
"data-width: 20",
"data-height: 21",
"data-framed: Not Framed",
"Group: Black On White",
"data-id: abstract",
"data-img: /img/black-on-white.jpg",
"data-title: Black On White",
"data-description: Acrylic on canvas",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Black Stripes",
"data-id: abstract",
"data-img: /img/black-stripes.jpg",
"data-title: Black Stripes",
"data-description: Acrylic on canvas",
"data-price: 175",
"data-width: 70",
"data-height: 50",
"data-framed: Not Framed",
"Group: Gray Square",
"data-id: abstract",
"data-img: /img/gray-square.jpg",
"data-title: Gray Square",
"data-description: Paper collage",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Harmony In White",
"data-id: abstract",
"data-img: /img/harmony-in-white.jpg",
"data-title: Harmony In White",
"data-description: Acrylic on canvas",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Mystic Sky",
"data-id: abstract",
"data-img: /img/mystic-sky.jpg",
"data-title: Mystic Sky",
"data-description: Paper collage and paint",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Red L",
"data-id: abstract",
"data-img: /img/red-l.jpg",
"data-title: Red L",
"data-description: Paper collage",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Red Stripe",
"data-id: abstract",
"data-img: /img/red-stripe.jpg",
"data-title: Red Stripe",
"data-description: Paper collage",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Study In Gray",
"data-id: abstract",
"data-img: /img/study-in-gray.jpg",
"data-title: Study In Gray",
"data-description: Collage and paint",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: White Boats",
"data-id: abstract",
"data-img: /img/white-boats.jpg",
"data-title: White Boats",
"data-description: Acrylic on cardboard",
"data-price: 40",
"data-width: 18",
"data-height: 21",
"data-framed: Not Framed",
"Group: White Field 2",
"data-id: abstract",
"data-img: /img/white-field-2.jpg",
"data-title: White Field 2",
"data-description: Paper collage",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: White Field",
"data-id: abstract",
"data-img: /img/white-field.jpg",
"data-title: White Field",
"data-description: Paper collage",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: White Post",
"data-id: abstract",
"data-img: /img/white-post.jpg",
"data-title: White Post",
"data-description: Paper collage and paint",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Yellow Corner",
"data-id: abstract",
"data-img: /img/yellow-corner.jpg",
"data-title: Yellow Corner",
"data-description: Acrylic on canvas",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Yellow Streak",
"data-id: abstract",
"data-img: /img/yellow-streak.jpg",
"data-title: Yellow Streak",
"data-description: Acrylic on canvas",
"data-price: 150",
"data-width: 40",
"data-height: 51",
"data-framed: Not Framed",
"Group: IMG 20200521 133017 Kindlephoto 267415499",
"data-id: abstract",
"data-img: /img/img_20200521_133017_kindlephoto-267415499.jpg",
"data-title: IMG 20200521 133017 Kindlephoto 267415499",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: IMG 20200521 133223 Kindlephoto 267580336",
"data-id: abstract",
"data-img: /img/img_20200521_133223_kindlephoto-267580336.jpg",
"data-title: IMG 20200521 133223 Kindlephoto 267580336",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: IMG 20200521 133116 Kindlephoto 267490243",
"data-id: abstract",
"data-img: /img/img_20200521_133116_kindlephoto-267490243.jpg",
"data-title: IMG 20200521 133116 Kindlephoto 267490243",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: One",
"data-id: collage",
"data-img: /img/one.jpg",
"data-title: One",
"data-description: Paper collage",
"data-price: 100",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Three",
"data-id: collage",
"data-img: /img/three.jpg",
"data-title: Three",
"data-description: Paper collage",
"data-price: 100",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Two",
"data-id: collage",
"data-img: /img/two.jpg",
"data-title: Two",
"data-description: Paper collage",
"data-price: 100",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Clyde Valley",
"data-id: landscapes",
"data-img: /img/clyde-valley.jpg",
"data-title: Clyde Valley",
"data-description: Acrylic on canvas",
"data-price: 240",
"data-width: 40",
"data-height: 50",
"data-framed: Not Framed",
"Group: Clyde Walkway 2",
"data-id: landscapes",
"data-img: /img/clyde-walkway-2.jpg",
"data-title: Clyde Walkway 2",
"data-description: Acrylic on canvas",
"data-price: 145",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Clyde Walkway",
"data-id: landscapes",
"data-img: /img/clyde-walkway.jpg",
"data-title: Clyde Walkway",
"data-description: Acrylic on canvas",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Falls Of Clyde 2",
"data-id: landscapes",
"data-img: /img/falls-of-clyde-2.jpg",
"data-title: Falls Of Clyde 2",
"data-description: Acrylic on canvas",
"data-price: 280",
"data-width: 40",
"data-height: 50",
"data-framed: Not Framed",
"Group: Falls Of Clyde Bonnington Linn",
"data-id: landscapes",
"data-img: /img/falls-of-clyde-bonnington-linn.jpg",
"data-title: Falls Of Clyde Bonnington Linn",
"data-description: Acrylic on canvas",
"data-price: 290",
"data-width: 40",
"data-height: 57",
"data-framed: Not Framed",
"Group: Falls Of Clyde",
"data-id: landscapes",
"data-img: /img/falls-of-clyde.jpg",
"data-title: Falls Of Clyde",
"data-description: Acrylic on canvas",
"data-price: 380",
"data-width: 50",
"data-height: 70",
"data-framed: Not Framed",
"Group: Findochty Harbour",
"data-id: landscapes",
"data-img: /img/findochty-harbour.jpg",
"data-title: Findochty Harbour",
"data-description: Acrylic on canvas",
"data-price: 170",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Frosty Garden",
"data-id: landscapes",
"data-img: /img/frosty-garden.jpg",
"data-title: Frosty Garden",
"data-description: Acrylic on canvas",
"data-price: 360",
"data-width: 57",
"data-height: 67",
"data-framed: Framed",
"Group: Frosty Morning Clyde Valley",
"data-id: landscapes",
"data-img: /img/frosty-morning-clyde-valley.jpg",
"data-title: Frosty Morning Clyde Valley",
"data-description: Acrylic on Canvas",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Frosy Morning Carnwath",
"data-id: landscapes",
"data-img: /img/frosy-morning-carnwath.jpg",
"data-title: Frosy Morning Carnwath",
"data-description: Acrylic on canvas",
"data-price: 280",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Lilac Copse",
"data-id: landscapes",
"data-img: /img/lilac-copse.jpg",
"data-title: Lilac Copse",
"data-description: Acrylic on canvas",
"data-price: 120",
"data-width: 23",
"data-height: 30",
"data-framed: Not Framed",
"Group: River Clyde 2",
"data-id: landscapes",
"data-img: /img/river-clyde-2.jpg",
"data-title: River Clyde 2",
"data-description: Heavily textured acrylic paint on canvas",
"data-price: 145",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: River Clyde Winter",
"data-id: landscapes",
"data-img: /img/river-clyde-winter.jpg",
"data-title: River Clyde Winter",
"data-description: Acrylic on Canvas",
"data-price: 350",
"data-width: 0",
"data-height: 0",
"data-framed: Framed",
"Group: River Clyde",
"data-id: landscapes",
"data-img: /img/river-clyde.jpg",
"data-title: River Clyde",
"data-description: Acrylic on board",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Snowscape",
"data-id: landscapes",
"data-img: /img/snowscape.jpg",
"data-title: Snowscape",
"data-description: Acrylic on canvas",
"data-price: 175",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"data-id: plasterPaintings",
"data-img: /img/snowscape.jpg",
"data-title: Snowscape",
"data-description: Plaster, acrylic paint on MDF.",
"data-price: 130",
"data-width: 25",
"data-height: 30",
"data-framed: Not Framed",
"Group: The Red Boat",
"data-id: landscapes",
"data-img: /img/the-red-boat.jpg",
"data-title: The Red Boat",
"data-description: Acrylic on Board",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Winter River Clyde",
"data-id: landscapes",
"data-img: /img/winter-river-clyde.jpg",
"data-title: Winter River Clyde",
"data-description: Watercolour on paper",
"data-price: 50",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: IMG 20210312 161841",
"data-id: landscapes",
"data-img: /img/img_20210312_161841.jpg",
"data-title: IMG 20210312 161841",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: 20211026 135812",
"data-id: landscapes",
"data-img: /img/20211026_135812.jpg",
"data-title: 20211026 135812",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: 20211028 123355",
"data-id: landscapes",
"data-img: /img/20211028_123355.jpg",
"data-title: 20211028 123355",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: By The Clyde",
"data-id: lockdown",
"data-img: /img/by-the-clyde.jpg",
"data-title: By The Clyde",
"data-description: Watercolour and pen and ink",
"data-price: 100",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"data-id: oilPastels",
"data-img: /img/by-the-clyde.jpg",
"data-title: By The Clyde",
"data-description: Tree by the river Clyde, oil pastel on black sugar paper",
"data-price: 100",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Dead Tree",
"data-id: lockdown",
"data-img: /img/dead-tree.jpg",
"data-title: Dead Tree",
"data-description: Watercolour and pen and ink",
"data-price: 100",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Imagined Landscape",
"data-id: lockdown",
"data-img: /img/imagined-landscape.jpg",
"data-title: Imagined Landscape",
"data-description: Imagined landscape based upon Tinto Hill. A slightly more expressive painting with lots of impostors paint",
"data-price: 300",
"data-width: 30",
"data-height: 40",
"data-framed: Not Framed",
"Group: Towards The Clyde Valley",
"data-id: lockdown",
"data-img: /img/towards-the-clyde-valley.jpg",
"data-title: Towards The Clyde Valley",
"data-description: Acrylic painted at scene,looking towards the Clyde Valley",
"data-price: 300",
"data-width: 30",
"data-height: 40",
"data-framed: Not Framed",
"Group: Tree 1",
"data-id: lockdown",
"data-img: /img/tree-1.jpg",
"data-title: Tree 1",
"data-description: Watercolour and pen and ink",
"data-price: 100",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Tree 2",
"data-id: lockdown",
"data-img: /img/tree-2.jpg",
"data-title: Tree 2",
"data-description: By the Clyde",
"data-price: 100",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Tree 3",
"data-id: lockdown",
"data-img: /img/tree-3.jpg",
"data-title: Tree 3",
"data-description: Over the bing",
"data-price: 100",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Tree 4",
"data-id: lockdown",
"data-img: /img/tree-4.jpg",
"data-title: Tree 4",
"data-description: Watercolour and pen and ink",
"data-price: 100",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Tree",
"data-id: lockdown",
"data-img: /img/tree.jpg",
"data-title: Tree",
"data-description: Watercolour and ink",
"data-price: 100",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"data-id: oilPastels",
"data-img: /img/tree.jpg",
"data-title: Tree",
"data-description: Oil pastel on paper",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Vista",
"data-id: lockdown",
"data-img: /img/vista.jpg",
"data-title: Vista",
"data-description: Watercolour painted an alien air",
"data-price: 100",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: IMG 20200513 145437 Kindlephoto 29950044",
"data-id: lockdown",
"data-img: /img/img_20200513_145437_kindlephoto-29950044.jpg",
"data-title: IMG 20200513 145437 Kindlephoto 29950044",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: IMG 20200630 125255 Kindlephoto 161020139",
"data-id: lockdown",
"data-img: /img/img_20200630_125255_kindlephoto-161020139.jpg",
"data-title: IMG 20200630 125255 Kindlephoto 161020139",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: IMG 20200508 155431 Kindlephoto 91266626",
"data-id: lockdown",
"data-img: /img/img_20200508_155431_kindlephoto-91266626.jpg",
"data-title: IMG 20200508 155431 Kindlephoto 91266626",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: IMG 20200630 125321 Kindlephoto 160944122",
"data-id: lockdown",
"data-img: /img/img_20200630_125321_kindlephoto-160944122.jpg",
"data-title: IMG 20200630 125321 Kindlephoto 160944122",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: IMG 20200508 155512 Kindlephoto 91688218",
"data-id: lockdown",
"data-img: /img/img_20200508_155512_kindlephoto-91688218.jpg",
"data-title: IMG 20200508 155512 Kindlephoto 91688218",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Clouds 2",
"data-id: oilPastels",
"data-img: /img/clouds-2.jpg",
"data-title: Clouds 2",
"data-description: Oil pastel on paper",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Clouds 3",
"data-id: oilPastels",
"data-img: /img/clouds-3.jpg",
"data-title: Clouds 3",
"data-description: Oil pastel on paper",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Clouds 4",
"data-id: oilPastels",
"data-img: /img/clouds-4.jpg",
"data-title: Clouds 4",
"data-description: Oil pastel on paper",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Clouds 5",
"data-id: oilPastels",
"data-img: /img/clouds-5.jpg",
"data-title: Clouds 5",
"data-description: Oil pastel on paper",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Clouds",
"data-id: oilPastels",
"data-img: /img/clouds.jpg",
"data-title: Clouds",
"data-description: Oil pastel on paper",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Coldingham Bay",
"data-id: oilPastels",
"data-img: /img/coldingham-bay.jpg",
"data-title: Coldingham Bay",
"data-description: Oil pastel on paper",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Self Portrait",
"data-id: oilPastels",
"data-img: /img/self-portrait.jpg",
"data-title: Self Portrait",
"data-description: Oil pastel on black sugar paper",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Skull 2",
"data-id: oilPastels",
"data-img: /img/skull-2.jpg",
"data-title: Skull 2",
"data-description: Oil pastel on black sugar paper",
"data-price: 100",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Skull 3",
"data-id: oilPastels",
"data-img: /img/skull-3.jpg",
"data-title: Skull 3",
"data-description: Oil Pastel",
"data-price: 100",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Skull",
"data-id: oilPastels",
"data-img: /img/skull.jpg",
"data-title: Skull",
"data-description: Oil pastel on black sugar paper",
"data-price: 120",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Weird Tree",
"data-id: oilPastels",
"data-img: /img/weird-tree.jpg",
"data-title: Weird Tree",
"data-description: Oil pastel on black sugar paper",
"data-price: 100",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Image",
"data-id: oilPastels",
"data-img: /img/image.jpg",
"data-title: Image",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: 20220922 155359",
"data-id: oilPastels",
"data-img: /img/20220922_155359.jpg",
"data-title: 20220922 155359",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: 20221110 143932",
"data-id: oilPastels",
"data-img: /img/20221110_143932.jpg",
"data-title: 20221110 143932",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: 20221110 145755",
"data-id: oilPastels",
"data-img: /img/20221110_145755.jpg",
"data-title: 20221110 145755",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: 20221230 150147",
"data-id: oilPastels",
"data-img: /img/20221230_150147.jpg",
"data-title: 20221230 150147",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Ailsa Craig",
"data-id: plasterPaintings",
"data-img: /img/ailsa-craig.jpg",
"data-title: Ailsa Craig",
"data-description: Plaster, acrylic paint on MDF",
"data-price: 130",
"data-width: 22",
"data-height: 31",
"data-framed: Not Framed",
"Group: Landscape With Cloud",
"data-id: plasterPaintings",
"data-img: /img/landscape-with-cloud.jpg",
"data-title: Landscape With Cloud",
"data-description: Plaster, acrylic paint on MDF.",
"data-price: 130",
"data-width: 25",
"data-height: 30",
"data-framed: Not Framed",
"Group: Purple Sky",
"data-id: plasterPaintings",
"data-img: /img/purple-sky.jpg",
"data-title: Purple Sky",
"data-description: Plaster, acrylic paint on board",
"data-price: 120",
"data-width: 20",
"data-height: 25",
"data-framed: Not Framed",
"Group: Red Landscape",
"data-id: plasterPaintings",
"data-img: /img/red-landscape.jpg",
"data-title: Red Landscape",
"data-description: Plaster, acrylic paint on MDF.",
"data-price: 130",
"data-width: 25",
"data-height: 30",
"data-framed: Not Framed",
"Group: Trees In The Distance",
"data-id: plasterPaintings",
"data-img: /img/trees-in-the-distance.jpg",
"data-title: Trees In The Distance",
"data-description: Plaster, acrylic paint on MDF.",
"data-price: 140",
"data-width: 30",
"data-height: 25",
"data-framed: Not Framed",
"Group: Trees On The Hill",
"data-id: plasterPaintings",
"data-img: /img/trees-on-the-hill.jpg",
"data-title: Trees On The Hill",
"data-description: Plaster with acrylic paint on MDF(medium density fibreboard)",
"data-price: 145",
"data-width: 25",
"data-height: 31",
"data-framed: Not Framed",
"Group: 20221230 150455",
"data-id: plasterPaintings",
"data-img: /img/20221230_150455.jpg",
"data-title: 20221230 150455",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: 20221230 150427 (1)",
"data-id: plasterPaintings",
"data-img: /img/20221230_150427.jpg",
"data-title: 20221230 150427 (1)",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: 20220704 151409",
"data-id: plasterPaintings",
"data-img: /img/20220704_151409.jpg",
"data-title: 20220704 151409",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: 20221230 150417 (1)",
"data-id: plasterPaintings",
"data-img: /img/20221230_150417.jpg",
"data-title: 20221230 150417 (1)",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: 20221230 150404 (1)",
"data-id: plasterPaintings",
"data-img: /img/20221230_150404.jpg",
"data-title: 20221230 150404 (1)",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: 20220627 163028",
"data-id: plasterPaintings",
"data-img: /img/20220627_163028.jpg",
"data-title: 20220627 163028",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: 20220922 152101",
"data-id: plasterPaintings",
"data-img: /img/20220922_152101.jpg",
"data-title: 20220922 152101",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Original 5Ec807d4 08F3 43A7 A3fa 96F634cfaa22 20220605 190015",
"data-id: plasterPaintings",
"data-img: /img/original_5ec807d4-08f3-43a7-a3fa-96f634cfaa22_20220605_190015.jpg",
"data-title: Original 5Ec807d4 08F3 43A7 A3fa 96F634cfaa22 20220605 190015",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Bird's Eye View",
"data-id: stAbbs",
"data-img: /img/bird-s-eye-view.jpg",
"data-title: Bird's Eye View",
"data-description: Watercolour on paper",
"data-price: 60",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Blue Boat",
"data-id: stAbbs",
"data-img: /img/blue-boat.jpg",
"data-title: Blue Boat",
"data-description: Watercolour and sharpies on paper",
"data-price: 75",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Fishing Boat",
"data-id: stAbbs",
"data-img: /img/fishing-boat.jpg",
"data-title: Fishing Boat",
"data-description: Watercolour on paper",
"data-price: 60",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Fishing Boats",
"data-id: stAbbs",
"data-img: /img/fishing-boats.jpg",
"data-title: Fishing Boats",
"data-description: Watercolour on paper",
"data-price: 95",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Harbour, St. Abbs",
"data-id: stAbbs",
"data-img: /img/harbour-st-abbs.jpg",
"data-title: Harbour, St. Abbs",
"data-description: Watercolour on paper",
"data-price: 75",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Harbour",
"data-id: stAbbs",
"data-img: /img/harbour.jpg",
"data-title: Harbour",
"data-description: Pen and Ink drawing",
"data-price: 60",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Red Fishing Boat",
"data-id: stAbbs",
"data-img: /img/red-fishing-boat.jpg",
"data-title: Red Fishing Boat",
"data-description: Acrylic on canvas paper",
"data-price: 95",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Red Reflections",
"data-id: stAbbs",
"data-img: /img/red-reflections.jpg",
"data-title: Red Reflections",
"data-description: Acrylic on canvas paper",
"data-price: 90",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Telephone Box",
"data-id: stAbbs",
"data-img: /img/telephone-box.jpg",
"data-title: Telephone Box",
"data-description: Watercolour on paper",
"data-price: 65",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: White Cottage",
"data-id: stAbbs",
"data-img: /img/white-cottage.jpg",
"data-title: White Cottage",
"data-description: Watercolour on paper",
"data-price: 55",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: IMG 20161020 123830",
"data-id: stAbbs",
"data-img: /img/img_20161020_123830.jpg",
"data-title: IMG 20161020 123830",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: IMG 20160706 113314",
"data-id: stAbbs",
"data-img: /img/img_20160706_113314.jpg",
"data-title: IMG 20160706 113314",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Blue 2",
"data-id: stillLife",
"data-img: /img/blue-2.jpg",
"data-title: Blue 2",
"data-description: Acrylic on canvas",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Blue Table",
"data-id: stillLife",
"data-img: /img/blue-table.jpg",
"data-title: Blue Table",
"data-description: Acrylic on canvas",
"data-price: 260",
"data-width: 50",
"data-height: 60",
"data-framed: Not Framed",
"Group: Blue",
"data-id: stillLife",
"data-img: /img/blue.jpg",
"data-title: Blue",
"data-description: Acrylic on canvas",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Dutch Still Life",
"data-id: stillLife",
"data-img: /img/dutch-still-life.jpg",
"data-title: Dutch Still Life",
"data-description: Acrylic on canvas",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Framed",
"Group: Pink Still Life",
"data-id: stillLife",
"data-img: /img/pink-still-life.jpg",
"data-title: Pink Still Life",
"data-description: Acrylic on canvas",
"data-price: 100",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Purple Table",
"data-id: stillLife",
"data-img: /img/purple-table.jpg",
"data-title: Purple Table",
"data-description: Acrylic on canvas",
"data-price: 275",
"data-width: 50",
"data-height: 60",
"data-framed: Not Framed",
"Group: Red Table",
"data-id: stillLife",
"data-img: /img/red-table.jpg",
"data-title: Red Table",
"data-description: Acrylic on canvas",
"data-price: 100",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Squinty Vase Of Flowers",
"data-id: stillLife",
"data-img: /img/squinty-vase-of-flowers.jpg",
"data-title: Squinty Vase Of Flowers",
"data-description: Acrylic on canvas",
"data-price: 300",
"data-width: 50",
"data-height: 70",
"data-framed: Not Framed",
"Group: Sunflower",
"data-id: stillLife",
"data-img: /img/sunflower.jpg",
"data-title: Sunflower",
"data-description: Acrylic on canvas",
"data-price: 240",
"data-width: 40",
"data-height: 50",
"data-framed: Not Framed",
"Group: Tulips",
"data-id: stillLife",
"data-img: /img/tulips.jpg",
"data-title: Tulips",
"data-description: Acrylic on canvas",
"data-price: 300",
"data-width: 50",
"data-height: 70",
"data-framed: Not Framed",
"Group: Vase Of Flowers",
"data-id: stillLife",
"data-img: /img/vase-of-flowers.jpg",
"data-title: Vase Of Flowers",
"data-description: Acrylic on canvas",
"data-price: 275",
"data-width: 50",
"data-height: 60",
"data-framed: Not Framed",
"Group: Blue Sky",
"data-id: italy",
"data-img: /img/blue-sky.jpg",
"data-title: Blue Sky",
"data-description: Acrylic on paper",
"data-price: 85",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Padua",
"data-id: italy",
"data-img: /img/padua.jpg",
"data-title: Padua",
"data-description: Watercolour on paper",
"data-price: 65",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Pink Building",
"data-id: italy",
"data-img: /img/pink-building.jpg",
"data-title: Pink Building",
"data-description: Acrlyic on paper",
"data-price: 75",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Pink Palace",
"data-id: italy",
"data-img: /img/pink-palace.jpg",
"data-title: Pink Palace",
"data-description: Acrylic on paper",
"data-price: 85",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Red Pavement",
"data-id: italy",
"data-img: /img/red-pavement.jpg",
"data-title: Red Pavement",
"data-description: Acrylic on paper",
"data-price: 75",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Squinty Building",
"data-id: italy",
"data-img: /img/squinty-building.jpg",
"data-title: Squinty Building",
"data-description: Acrylic on paper",
"data-price: 75",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Street Light",
"data-id: italy",
"data-img: /img/street-light.jpg",
"data-title: Street Light",
"data-description: Watercolour on paper",
"data-price: 60",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Street Scene",
"data-id: italy",
"data-img: /img/street-scene.jpg",
"data-title: Street Scene",
"data-description: Watercolour on paper",
"data-price: 55",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Study",
"data-id: italy",
"data-img: /img/study.jpg",
"data-title: Study",
"data-description: Pen and wash on paper",
"data-price: 60",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Venetian Building",
"data-id: italy",
"data-img: /img/venetian-building.jpg",
"data-title: Venetian Building",
"data-description: Watercolour painting",
"data-price: 60",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Venetian Buildings",
"data-id: italy",
"data-img: /img/venetian-buildings.jpg",
"data-title: Venetian Buildings",
"data-description: Watercolour on paper",
"data-price: 55",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Venetian Street Scene",
"data-id: italy",
"data-img: /img/venetian-street-scene.jpg",
"data-title: Venetian Street Scene",
"data-description: Pen drawing",
"data-price: 75",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: Venetian Theatre",
"data-id: italy",
"data-img: /img/venetian-theatre.jpg",
"data-title: Venetian Theatre",
"data-description: Watercolour on paper",
"data-price: 75",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: View From Hotel",
"data-id: italy",
"data-img: /img/view-from-hotel.jpg",
"data-title: View From Hotel",
"data-description: Watercolour",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: IMG 20161020 123403",
"data-id: italy",
"data-img: /img/img_20161020_123403.jpg",
"data-title: IMG 20161020 123403",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: IMG 20180504 170620",
"data-id: italy",
"data-img: /img/img_20180504_170620.jpg",
"data-title: IMG 20180504 170620",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: IMG 20150404 1821582",
"data-id: italy",
"data-img: /img/img_20150404_182158-2.jpg",
"data-title: IMG 20150404 1821582",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: IMG 20150404 18214122",
"data-id: italy",
"data-img: /img/img_20150404_182141-2-2.jpg",
"data-title: IMG 20150404 18214122",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: IMG 20150404 1824252",
"data-id: italy",
"data-img: /img/img_20150404_182425-2.jpg",
"data-title: IMG 20150404 1824252",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: IMG 20180504 170703 1",
"data-id: italy",
"data-img: /img/img_20180504_170703_1.jpg",
"data-title: IMG 20180504 170703 1",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: 2012 09 02 16.01.09",
"data-id: italy",
"data-img: /img/2012-09-02-16-01-09.jpg",
"data-title: 2012 09 02 16.01.09",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: IMG 20150404 18251822",
"data-id: italy",
"data-img: /img/img_20150404_182518-2-2.jpg",
"data-title: IMG 20150404 18251822",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed",
"Group: IMG 20150404 1825552",
"data-id: italy",
"data-img: /img/img_20150404_182555-2.jpg",
"data-title: IMG 20150404 1825552",
"data-description: ",
"data-price: 0",
"data-width: 0",
"data-height: 0",
"data-framed: Not Framed ",
]


# Initialize a dictionary to store attributes for each group
group_attributes = {}

# Initialize a dictionary to hold the current group's attributes
current_attributes = {}

# Iterate over the data list
for item in data:
    if item.startswith("Group: "):
        # Store previous group's attributes and reset the current attributes dictionary
        if current_attributes:
            group_id = current_attributes.get('data-id', 'default')  # Use a default ID if not present
            if group_id not in group_attributes:
                group_attributes[group_id] = []
            group_attributes[group_id].append(current_attributes)
        current_attributes = {'Group': item.replace("Group: ", "")}
    else:
        key, value = item.split(': ', 1)
        current_attributes[key] = value

# Append the last group's attributes
if current_attributes:
    group_id = current_attributes.get('data-id', 'default')  # Use a default ID if not present
    if group_id not in group_attributes:
        group_attributes[group_id] = []
    group_attributes[group_id].append(current_attributes)

# Create and write the populated templates for each group to separate HTML files
for group_id, attributes_list in group_attributes.items():
    with open(f'_src/partials/gallerylist_{group_id}.html', 'w') as html_file:
        for attributes in attributes_list:
            template = f"${{require('/partials/card.html') title=`{attributes.get('data-title', '')}` id=`{attributes.get('data-id', '')}` img=`{attributes.get('data-img', '')}` description=`{attributes.get('data-description', '')}` price=`{attributes.get('data-price', '')}` width=`{attributes.get('data-width', '')}` height=`{attributes.get('data-height', '')}` frame=`{attributes.get('data-framed', '')}`}}"
            html_file.write(template + '\n')
